// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Input: typeof import('./src/components/form/Input.vue')['default']
    LogoutModal: typeof import('./src/components/modals/LogoutModal.vue')['default']
    Message: typeof import('./src/components/chat/Message.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModalBookingContactData: typeof import('./src/components/modals/ModalBookingContactData.vue')['default']
    NavBar: typeof import('./src/components/nav/NavBar.vue')['default']
    NavSideBar: typeof import('./src/components/nav/NavSideBar.vue')['default']
    NavTopBar: typeof import('./src/components/nav/NavTopBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
